export const theme = {
  colors: {
    primary: '#ff7a00',
    text: '#333',
    background: '#f5f5f5',
    backgroundDark: '#252525',
    footerBackground: 'white',
    footerText: 'black',
    footerLink: 'white',
    footerLinkHover: '#f0a500',
    headerGradientEnd: '#444',
    headerText: 'white',
    bookmarkIcon: '#e0a449',
    cardBackground: 'white',
    cardShadow: 'rgba(0, 0, 0, 0.1)',
    imagePlaceholder: '#e0e0e0',
    imagePlaceholderText: '#999',
    cardStatus: '#666',
  },
  fonts: {
    main: 'Roboto, sans-serif',
    code: 'source-code-pro, Menlo, Monaco, Consolas, "Courier New", monospace',
  },
  spacing: {
    small: '1rem',
    medium: '2rem',
    large: '5rem',
    footerPadding: '1rem',
  },
  boxShadow: '0 0.125rem 0.3125rem rgba(0, 0, 0, 0.1)',
  borderRadius: '0.625rem',
};
